# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 13.0.1

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-3
    ports:
      - 80:8000
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ./src:/var/www/html:delegated
      - ~/.composer:/var/www/html/var/composer_home:delegated
      - ~/.composer:/var/www/.composer:delegated
      - ./Api:/var/www/html/app/code/AllInData/ContentFuzzyfyr/Api:cached
      - ./assets:/var/www/html/app/code/AllInData/ContentFuzzyfyr/assets:cached
      - ./Block:/var/www/html/app/code/AllInData/ContentFuzzyfyr/Block:cached
      - ./Console:/var/www/html/app/code/AllInData/ContentFuzzyfyr/Console:cached
      - ./etc:/var/www/html/app/code/AllInData/ContentFuzzyfyr/etc
      - ./Handler:/var/www/html/app/code/AllInData/ContentFuzzyfyr/Handler:cached
      - ./i18n:/var/www/html/app/code/AllInData/ContentFuzzyfyr/i18n:cached
      - ./Model:/var/www/html/app/code/AllInData/ContentFuzzyfyr/Model:cached
      - ./Observer:/var/www/html/app/code/AllInData/ContentFuzzyfyr/Observer:cached
      - ./Test:/var/www/html/app/code/AllInData/ContentFuzzyfyr/Test:cached
      - ./registration.php:/var/www/html/app/code/AllInData/ContentFuzzyfyr/registration.php
      - sockdata:/sock

  phpfpm:
    image: markoshust/magento-php:7.1-fpm
    links:
      - db
    volumes: *appvolumes

  cron:
    image: markoshust/magento-php:7.1-fpm
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - 3306:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  sockdata:
